version: "3.8"

services:
    laborator2-api:
        image: mobylab/idp-laborator2-api
        # build: .
        ports:
            - 5555:80
        environment:
            PGUSER: admin
            PGPASSWORD: admin
            PGHOST: laborator2-db
            PGDATABASE: books
            PGPORT: 5432
        networks:
            - laborator2-db-network
        depends_on:
            - laborator2-db

    laborator2-db:
        image: postgres:12
        environment:
            POSTGRES_DB: books
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
        volumes:
            - "${PWD}/Database/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql"
            - laborator2-db-persistent-volume:/var/lib/postgresql/data
        networks:
            - laborator2-db-network

volumes:
    laborator2-db-persistent-volume:

networks:
    laborator2-db-network:
