version: "3.8"

services:
    gateway:
        image: mobylab/idp-laborator3-gateway
        ports:
            - 3000:80
        environment:
            BOOKS_SERVICE_API_ROUTE: books-service/api
            NODE_ENV: development
        deploy:
            replicas: 3
            placement:
                max_replicas_per_node: 2
            update_config:
                parallelism: 2
                order: start-first
            rollback_config:
                parallelism: 2
                order: stop-first
        networks:
            - internal
  
    books-service:
        image: mobylab/idp-laborator3-books
        environment:
            IO_SERVICE_API_ROUTE: io-service/api
            NODE_ENV: development
        deploy:
            replicas: 2
            placement:
                max_replicas_per_node: 1
            update_config:
                order: start-first
            rollback_config:
                order: stop-first
        networks:
            - internal
            - books

    io-service:
        image: mobylab/idp-laborator3-io
        environment:
            PGUSER_FILE: lab3-user-secret
            PGPASSWORD_FILE: lab3-password-secret
            PGHOST: db
            PGPORT: 5432
            PGDATABASE: books
            NODE_ENV: staging
        deploy:
            replicas: 3
            placement:
                max_replicas_per_node: 2
            update_config:
                order: start-first
            rollback_config:
                order: stop-first
        secrets: 
            - lab3-user-secret
            - lab3-password-secret
        networks:
            - books
            - database

    db:
        image: postgres:12
        environment:
            POSTGRES_DB: books
            POSTGRES_USER_FILE: /run/secrets/lab3-user-secret
            POSTGRES_PASSWORD_FILE: /run/secrets/lab3-password-secret
        deploy:
            placement:
                constraints:
                    - "node.role==manager"
        secrets: 
            - lab3-user-secret
            - lab3-password-secret
        volumes:
            - ./Database/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
            - db-volume:/var/lib/postgresql/data
        networks:
            - database
            - database-admin

    adminer:
        image: adminer
        ports:
            - 8080:8080
        networks:
            - database-admin

volumes:
    db-volume:

networks:
    internal:
    books:
    database:
    database-admin:

secrets:
    lab3-user-secret:
        external: true
    lab3-password-secret:
        external: true
