apiVersion: v1
kind: Pod
metadata:
  name: db-pod
  labels:
    app: postgres
spec:
  containers:
    - image: postgres:10.4
      name: postgres
      volumeMounts:
      - name: myvol
        mountPath: /etc/config
      ports:
        - containerPort: 5432
      envFrom:
        - configMapRef:
            name: db-config-map
  volumes:
    - name: myvol
      persistentVolumeClaim:
        claimName: postgress-pvc