apiVersion: v1
kind: Pod
metadata:
  name: testapp
spec:
  containers:
    - image: raduioanciobanu/cloudcomputing:example
      name: testapp
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "200m"
          memory: "256Mi"
      ports:
        - containerPort: 5000
          name: http
          protocol: TCP
